name: Markdown Lint

on:
    push:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: markdownlint-cli2-action
              uses: DavidAnson/markdownlint-cli2-action@v19.0.0
              with:
                  fix: true
                  globs: |
                    README.md
                    CONTRIBUTING.md

